module.exports = {
    "opts": {
        "encoding": "utf8",
        "readme": "./README.md",
        "destination": "docs/",
        "recurse": true,
        "verbose": true,
        "template": "./node_modules/tui-jsdoc-template"
    },
    "tags": {
        "allowUnknownTags": true
    },
    "source": {
        "include": ["./src"],
        "exclude": [],
        "includePattern": ".+\\.(js|jsdoc|jsx|vue)$",
        "excludePattern": ""
    },
    "plugins": [
        "jsdoc-vuejs",
        "jsdoc-vuex-plugin"
    ],
    "templates": {
        "name": "UKRN Workshop Builder Tool",
        "cleverLinks": true,
        "monospaceLinks": false,
        "footerText": "Documentation generated by JSDOC. Template by TOAST UI.",
        "tabNames": {
            "api": "API",
            "tutorials": "Examples"
        },
        "default": {
            "staticFiles": {
                "include": ["src/assets/style"]
            }
        },
        "css": [
            "jsdoc-tweaks.css"
        ]
    }
}
