name: Parallel Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Non-master suffix--
        if: env.BRANCH != 'master' && env.BRANCH != 'main'
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})--" >> $GITHUB_ENV

      - name: Remove master branch name
        if: env.BRANCH == 'master' || env.BRANCH == 'main'
        run: echo "BRANCH="" >> $GITHUB_ENV

      - name: Set base Cypress Base URL
        run: echo "CYPRESS_BASE_URL=https://$(echo ${{ env.BRANCH }})ukrn-wb.netlify.app" >> $GITHUB_ENV

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'Actions example'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
